g:
	g++ -Wall -fsanitize=address -g create_graph.cpp ../onegin/fileReader.c ../akinator/data/dataBaseRead.cpp ../binary_tree/BinaryTree.cpp -o graph
d:
	g++ -Wall -g -DDEBUG create_graph.cpp ../onegin/fileReader.c ../akinator/data/dataBaseRead.cpp ../common/log.cpp ../binary_tree/BinaryTree.cpp -o graph
r:
	valgrind ./graph